server:
  port: 1081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12365/eureka
spring:
  application:
    name: service-feign
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"

