eureka:
  client:
    service-url:
      defaultZone: http://localhost:12365/eureka
server:
  port: 12581
spring:
  application:
    name: service-zuul
  main:
    allow-bean-definition-overriding: false
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    feign:
      path: /api-feign/**
      serviceId: service-feign
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000