eureka:
  client:
    service-url:
      defaultZone: http://localhost:12365/eureka
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/perryDavid/springcloudTest
          search-paths: springcloudtest/ConfigProperties
  application:
    name: config-server
server:
  port: 12367
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
