eureka:
  client:
    service-url:
      defaultZone: http://localhost:12365/eureka
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/perryDavid/springcloudTest
          search-paths: springcloudtest/ConfigProperties
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: david
    password: 123456
    virtual-host: david
server:
  port: 12367
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

