eureka:
  client:
    service-url:
      defaultZone: http://localhost:12365/eureka
server:
  port: 12367
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/perryDavid/springcloudTest
          search-paths: springcloudtest/ConfigProperties

