server:
  port: 1788
spring:
  application:
    name: service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12365/eureka
management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"