server:
  port: 12368
management:
  server:
    port: 12368
  endpoints:
    web:
      exposure:
        include: refresh,health,info
spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    username: david
    password: 123456
    virtual-host: david